### PR TITLE
Add explicit code generation target to pyclif. 

### PR DESCRIPTION
**Pull request by r9y9**
"--py3output" option needs to be passed to pyclif

### CODE REVIEW

**Comment by dogancan** [comment]
Hey @r9y9. Thanks for the PR.

I guess this option might be needed if you build/install pyclif with python2 and then build pykaldi with python3. Is that what happened in your case? 

I am asking since we did not need this flag with either python version up until now. Also, what happens in the alternative scenario where pyclif is built with python3 but user tries to install pykaldi with python2. I am guessing the else case of the major version check you added should set `--py3output` to `False` instead of omitting it since otherwise pyclif will set it to `True` based on which python version it was built with.

**Comment by r9y9** [comment]
> I guess this option might be needed if you build/install pyclif with python2 and then build pykaldi with python3. Is that what happened in your case?

Yes, exactly. I tried to build clif with python3, but it failed due to some reason. Using python2 simply worked for me. I will try the alternative case and see what happens.

**Comment by dogancan** [comment]
CLIF installation sometimes fails if both python2 and python3 is installed. See if adding the following lines to the cmake call in `clif/INSTALL.sh` helps.
```
cmake ... \
  -DPYTHON_INCLUDE_DIR="/usr/include/python3.6" \
  -DPYTHON_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython3.6m.so" \
  -DPYTHON_EXECUTABLE="/usr/bin/python3.6" \
  "${CMAKE_G_FLAGS[@]}" "$LLVM_DIR/llvm"
```
You might have to adjust the paths if python3 is installed somewhere else on your system or if you want to build with a different minor version of python3.

**Comment by r9y9** [comment]
For the record, I used the following cmake command to compile CLIF:

```
cmake -DPYTHON_INCLUDE_DIR="$HOME/anaconda3/include/python3.6m" \
      -DPYTHON_LIBRARY="$HOME/anaconda3/lib/libpython3.6m.so" \
      -DPYTHON_EXECUTABLE="$HOME/anaconda3/bin/python" \
      -DCMAKE_INSTALL_PREFIX="$CLIF_VIRTUALENV/clang" \
      -DCMAKE_PREFIX_PATH="$PROTOC_PREFIX_PATH" \
      -DLLVM_INSTALL_TOOLCHAIN_ONLY=true \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_BUILD_DOCS=false \
      -DLLVM_TARGETS_TO_BUILD=X86 \
      "${CMAKE_G_FLAGS[@]}" "$LLVM_DIR/llvm"
```

**Comment by dogancan** [comment]
Setting `default=False` for `--py3output` sounds reasonable for our CLIF fork but I don't think it will work for the upstream CLIF repo since they will probably want to keep backward compatibility. 

How about adding a new `--py2output` option, making `--py2output` and `--py3output` a mutually exclusive argument group, and setting both of them to `default=False`? Then we can check after parsing the command line to see if one of them were present and fall back to `sys.version_info.major` if neither was set.

**Comment by r9y9** [comment]
That sounds better! I will create a PR.

**Comment by dogancan** [comment]
I guess with the change in pyclif parser, we now want `--py2output` in the else case of the check in cmake. Do you mind making that change as well?

**Comment by dogancan** [comment]
Thanks!

**Comment by r9y9** [comment]
My pleasure. Thank you for the great project!

**Pull request merged**
