### PR TITLE
Support to MleDiagGmmUpdate, MapDiagGmmUpdate and MlObjective functions

### PR DESCRIPTION
**Pull request by mxmpl**
I added support to MleDiagGmmUpdate, MapDiagGmmUpdate and MlObjective functions.

### CODE REVIEW

**Comment by mmmaat** [comment]
Hi @vrmpx,
I know pykaldi is somewhat unmaintained for months now, but would it be possible to merge this PR? We need it to support VTLN training in our toolbox [shennong](https://github.com/bootphon/shennong). For now we are using a custom [fork](https://github.com/bootphon/shennong-pykaldi) but this would be really nice for us to use the mainline pykaldi instead.

**Comment by bmilde** [comment]
Hi @mmmaat,

Thanks for your pull request! While pykaldi has been unmaintained for a couple of months, a new major release is coming very soon (0.2). I'll first merge the recent changes to get pykaldi to compile with Python 3.8 + a 2021 version of Kaldi, then I'll try your merge your PR on top of the new version. Looks straightforward enough that there shouldn't be any problems.

We should be able to get this it into the 0.2 version as well.

**Comment by bmilde** [comment]
Hi, I've just merged the changes for PyKaldi 0.2 into the master. Can you quickly check if you can compile the new version with your changes? You should use a recent version of Python, either 3.8 or 3.9. Thank you!

**Comment by mmmaat** [comment]
Ok thanks! I'm doing it and let you know if it works.
[not related to this PR] I started the compilation from a fresh clone, and got an error during clif compilation [here](https://github.com/pykaldi/pykaldi/blob/8f8775fa4aa23c852351e826b40a271ebef55532/tools/install_clif.sh#L175). On Ubuntu-20.04 with gcc9.

**Comment by bmilde** [comment]
Probably the same as https://github.com/pykaldi/pykaldi/issues/232 ?

Current workaround is to downgrade gcc to 7.4 (you can install multiple gcc
versions on Ubuntu)

Am Do., 27. Mai 2021 um 18:23 Uhr schrieb Mathieu Bernard <
***@***.***>:

**Comment by mmmaat** [comment]
Thanks! Actually applying https://bugzilla.redhat.com/attachment.cgi?id=1389687&action=diff works with gcc9. You can patch it with one line of `sed` in `install_clif.sh` (I can do a PR if you want to).

**Comment by bmilde** [comment]
Yes, please make a PR! Thanks for trying that fix out and nice to know that it was all it took to make it compile with gcc 9 :)

**Comment by mmmaat** [comment]
Ok... so I managed to build and install pykaldi-02 with this PR226. This PR seems to work because the related tests in Shennong are all passing (related to VTLN). But the pykaldi tests for nnet3 fail, this seems related to the `text_utils` module you added. A minimal example:
```python
from kaldi.util._text_utils import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c9b72573f064> in <module>
----> 1 from kaldi.util._text_utils import *

ImportError: /home/****/pykaldi/kaldi/util/_text_utils.so: undefined symbol: _ZSt12Clif_PyObjAsP7_objectPPSi
```
Also I think the `KALDI_ASSERT` from Kaldi is now causing a crash (in former pykaldi it raised a RuntimeError). Here a minimal example:
```python
import kaldi.gmm
gmm = kaldi.gmm.DiagGmm(8, 13)
# by commenting this line I reach the KaldiAssert in https://github.com/kaldi-asr/kaldi/blob/0c51c8d55215f2f07783b517594d4ae565031dab/src/gmm/diag-gmm.h#L175
# gmm.compute_gconsts()
gmm.gconst()  # this crach now, was a RuntimeError
```
Hope this helps!

**Comment by bmilde** [comment]
Thanks, merging your changes! I assume thats some extra tests that you have with shennong? Because I wasn't getting alerted to any problems with text-utils by the pykaldi tests. Maybe we can some of your tests as well to pykaldi?

text-utils didn't have any CLIF_DEPS in the cmake file (but it has now). Then it compiles without errors but there are linking problems at runtime. 

For the RuntimeError / KALDI_ASSERT / crash, I wasn't able to reproduce this. Probably best if you'd open a separate issue.

Looking forward to a PR for the compliation gcc bug as well :)

**Comment by mmmaat** [comment]
Thanks for the merge!

About text-utils, it works now. About the PR, it works. About the KALDI_ASSERT stuff, I'm not sure, I guess it is changes in Kaldi code itself so I just updated the shennong code and now it's OK.

**Comment by bmilde** [comment]
Glad to hear that it works! :) I've committed a potential fix for the
KALDI_ASSERT stuff, but you need to pull the changes in the pykaldi_02
branch of Kaldi in tools/kaldi. Please give it a try, thank you!



Am Fr., 28. Mai 2021 um 18:43 Uhr schrieb Mathieu Bernard <
***@***.***>:

**Comment by mmmaat** [comment]
I tried your fix on KADI_ASSERT. Now my example above (`gmm.gconsts()`) do not crash anymore but outputs the message `ASSERTION_FAILED ([5.5.950-085be]:gconsts():gmm/diag-gmm.h:175) Assertion failed: (valid_gconsts_)` without throwing an exception. I guess the expected behavior here would be to throw a RuntimeError.

(I don't know how critical is that bug, it is just a piece of piece of shennong that is based on that, see [here](https://github.com/bootphon/shennong/blob/master/shennong/processor/ubm.py#L256), I fount an alternative implementation anyway)
(not opening a new issue, feel free to do it)

**Pull request merged**
